;;; M3 suite (DESIGN.md §8 M3): typed conditions from :errors, and the §3.2
;;; transcript behaviors (condition class + use-value restart). Runs against
;;; the MACRO-based examples/wordbag via run-m3.lisp (which also re-runs the
;;; full M1/M2 suites against it — gate (b)); the golden byte-identity gate
;;; (a) is fx.golden-manifest running against the macro crate's manifest.

(in-package #:rulisp/test)

(def-suite* :rulisp-m3)

(test m3.typed-conditions
  "Manifest :errors generate condition classes: WORDBAG:PARSE-ERROR is a
subclass of RULISP:RUST-ERROR and is what parse-number signals."
  (ensure-crate)
  (let ((cond-sym (find-symbol "PARSE-ERROR" "WORDBAG")))
    (is (not (null cond-sym)))
    (is (subtypep cond-sym 'rulisp:rust-error))
    (let ((c (handler-case (progn (wb-call "PARSE-NUMBER" "42x") nil)
               (rulisp:rust-error (e) e))))
      (is (typep c cond-sym))
      (is (string= "ParseError" (rulisp:rust-error-type c)))
      ;; the generic error type is NOT a typed condition
      (let ((bag (make-bag)))
        (let ((g (handler-case (progn (wb-call "WORD-BAG-ADD" bag "") nil)
                   (rulisp:rust-error (e) e))))
          (is (not (typep g cond-sym)))
          (is (string= "Error" (rulisp:rust-error-type g))))
        (rulisp:free bag)))))

(test m3.transcript
  "§3.2 transcript: parse-number \"42x\" → WORDBAG:PARSE-ERROR with the
exact message, offering a USE-VALUE restart."
  (ensure-crate)
  (let ((cond-sym (find-symbol "PARSE-ERROR" "WORDBAG")))
    (handler-bind ((rulisp:rust-error
                     (lambda (c)
                       (is (typep c cond-sym))
                       (is (string= "invalid digit found in string: \"42x\""
                                    (rulisp:rust-error-message c)))
                       (is (find 'use-value (compute-restarts c)
                                 :key #'restart-name))
                       (use-value 0 c))))
      (is (= 0 (wb-call "PARSE-NUMBER" "42x"))))))

(test m3.macro-crate-loaded
  "Sanity: the crate under test is generated by macros (examples/wordbag),
not the hand-written oracle."
  (ensure-crate)
  (is (search "examples/wordbag"
              (namestring (rulisp::crate-source-path *crate*)))))
